title: "Workshop: Climate Impacts and Adaptation"
description: "April 16-17, 2026 • Frankfurt am Main • Goethe University"
# theme: jekyll-theme-cayman   # <- remove or comment out; we’ll use our own layout/CSS
markdown: kramdown
